# allows access to UI components to show flow logs, audit logs, stats
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ui-traffic-stats
rules:
- apiGroups: [""]
  resources: ["services/proxy"]
  resourceNames: ["https:tigera-api:8080", "calico-node-prometheus:9090"]
  verbs: ["get","create"]
# Access to flow logs, audit logs, and statistics
- apiGroups: ["lma.tigera.io"]
  resources: ["*"]
  # access to specific resources
  resourceNames: ["flows", "audit*", "events", "dns"]
  verbs: ["get"]
- apiGroups: ["projectcalico.org"]
  resources: ["authenticationreviews","authorizationreviews"]
  verbs: ["create"]
---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ui-policy-board-reader
rules:
- apiGroups: ["networking.k8s.io","extensions",""]
  resources: ["networkpolicies","namespaces"]
  verbs: ["get","watch","list"]
- apiGroups: ["projectcalico.org"]
  resources: ["tiers","tier.networkpolicies","tier.globalnetworkpolicies"]
  verbs: ["get","watch","list"]
# access to see policy board
- apiGroups: ["projectcalico.org"]
  resources: ["clusterinformations"]
  verbs: ["get","list"]
---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: security-tier-policy-cruder
rules:
# To access Calico policy in a tier, the user requires get access to that tier.
- apiGroups: ["projectcalico.org"]
  resources: ["tiers"]
  resourceNames: ["security"]
  verbs: ["get"]
# This allows configuration of all types of NetworkPolicy resources in the security tier as well as NetworkSet resources.
- apiGroups: ["projectcalico.org"]
  resources: ["tier.networkpolicies","tier.globalnetworkpolicies","tier.stagedkubernetesnetworkpolicies","stagedkubernetesnetworkpolicies","globalnetworksets","networksets"]
  resourceNames: ["security.*"]
  verbs: ["*"]
- apiGroups: ["projectcalico.org"]
  resources: ["networksets","globalnetworksets"]
  verbs: ["get","watch","list"]
- apiGroups: ["projectcalico.org"]
  resources: ["globalalerts","globalalerts/status","globalalerttemplates"]
  verbs: ["get","watch","list"]
---

##############################################
# allow full access to security tier
##############################################
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: security-full-access
subjects:
- kind: ServiceAccount
  name: secuser
  namespace: default
roleRef:
  kind: ClusterRole
  name: security-tier-policy-cruder
  apiGroup: rbac.authorization.k8s.io
---

##############################################
# grant access to APIs in Enterprise Manager UI
##############################################
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tmui-traffic-stats-access
subjects:
- kind: ServiceAccount
  name: secuser
  namespace: default
roleRef:
  kind: ClusterRole
  name: ui-traffic-stats
  apiGroup: rbac.authorization.k8s.io
---

##############################################
# grant access to Enterpris Manager policy board view
##############################################
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tmui-policy-board-access
subjects:
- kind: ServiceAccount
  name: secuser
  namespace: default
roleRef:
  kind: ClusterRole
  name: ui-policy-board-reader
  apiGroup: rbac.authorization.k8s.io
