
apiVersion: projectcalico.org/v3
kind: NetworkSet
metadata:
  name: app1-trusted-domains
  namespace: app1
  labels:
    external-ep: app1-trusted-domains
spec:
  allowedEgressDomains:
    - 'github.com'
