apiVersion: apps/v1
kind: Deployment
metadata:
  name: attacker-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: attacker-app
  template:
    metadata:
      labels:
        app: attacker-app
    spec:
      containers:
        - name: attacker-app
          image: gcr.io/tigera-demo/attacker-pod:1.0.1
